##
# Local development override for docker-compose.yml.
#
# This file overrides docker-compose.yml with local development practices.
#
# Overrides:
# Replaces the standard volume mount that shares code into the Docker
# container with a named volume managed by Outrigger.
#
# Run 'rig project sync' to start syncing.
# @see http://docs.outrigger.sh/project-setup/filesystem-sync/
#
# This configuration is automatically applied by default (when you **do not**
# specify the `-f` flag.)
#
# To skip including this configuration, run 'docker-compose -f docker-compose.yml ...'
##
version: '3.3'

services:
  www:
    volumes:
      - drupal8-sync:/var/www

volumes:
  drupal8-sync:
    external: true
