version: '3.3'

services:
  
  # View at http://ui.swagger.vm:8080
  # docker-compose up -d ui
  # For environment variable options, see https://github.com/swagger-api/swagger-ui/blob/master/Dockerfile
  ui:
    container_name: swagger_${DOCKER_ENV:-local}_ui
    environment:
      API_URL: http://generator.swagger.io/api/swagger.json
    image: swaggerapi/swagger-ui:v3.7.0
    labels:
      com.dnsdock.name: ui
      com.dnsdock.image: swagger
      vcs-app-url: https://github.com/swagger-api/swagger-ui
    network_mode: bridge
    ports:
      # @TODO port mapping fails.
      - 80:8080

  # View at http://editor.swagger.vm:8080
  # docker-compose up -d editor
  editor:
    container_name: swagger_${DOCKER_ENV:-local}_editor
    image: swaggerapi/swagger-editor:v3.1.20
    labels:
      com.dnsdock.name: editor
      com.dnsdock.image: swagger
      vcs-app-url: https://github.com/swagger-api/swagger-editor
    network_mode: bridge
    ports:
      # @TODO port mapping fails.
      - 80:8080

  # Web-service version of generator-cli
  # docker-compose up -d generator
  generator:
    container_name: swagger_${DOCKER_ENV:-local}_generator_web
    environment:
      GENERATOR_HOST: http://generator.swagger.vm
    image: swaggerapi/swagger-editor:v3.1.20
    labels:
      com.dnsdock.name: generator
      com.dnsdock.image: swagger
      vcs-app-url: https://github.com/swagger-api/swagger-codegen
      org.label-schema.usage: https://github.com/swagger-api/swagger-codegen#swagger-generator-docker-image
    network_mode: bridge
    ports:
      - 80:8080
  
  # SWAGGER_LANGUAGE=php docker-compose run --rm generator-cli
  generator-cli:
    image: swaggerapi/swagger-codegen-cli:latest
    command:
      - "generate"
      - "-i"
      - "http://petstore.swagger.io/v2/swagger.json"
      - "-l"
      - "${SWAGGER_LANGUAGE:-go}"
      - "-o"
      - "/code/${SWAGGER_LANGUAGE:-go}"
    labels:
      vcs-app-url: https://github.com/swagger-api/swagger-codegen
      org.label-schema.usage: https://github.com/swagger-api/swagger-codegen#swagger-codegen-cli-docker-image
    network_mode: bridge
    volumes:
      - ${SWAGGER_GENERATOR_DIR:-./build}:/code
  
